package rules

import com.agency.*;

rule "Offer Greece"
	salience 10000
    when
    	not Fact(name("poland"), value(true))
    	Fact(name("seaside"), value(true))
    	Fact(name("sightseeing"), value(true))
    	Fact(name("objazd"), value(true))
			not Fact(name("fear_earthquakes"), value(true))
			not Fact(name("exotic"), value(true))
    then
    	Communication.askQuestion("greece");
end

rule "Offer Turkey"
	salience 10000
    when
    	not Fact(name("poland"), value(true))
    	Fact(name("seaside"), value(true))
    	Fact(name("sightseeing"), value(true))
			not Fact(name("fear_earthquakes"), value(true))
			not Fact(name("jungle"), value(true))
    then
    	Communication.askQuestion("turkey");
end

rule "Offer Australia"
	salience 10000
    when
    	not Fact(name("poland"), value(true))
    	Fact(name("long_flight"), value(true))
    	Fact(name("surfing"), value(true))
    	not Fact(name("objazd"), value(true))
			not Fact(name("jungle"), value(true))
    then
    	Communication.askQuestion("australia");
end

rule "Offer Kolobrzeg"
	salience 10000
	when
		Fact(name("seaside"), value(true))
		not Fact(name("objazd"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("kolobrzeg");
end

rule "Offer Zakopane"
	salience 10000
	when
		Fact(name("skiing"), value(true))
		Fact(name("mountains"), value(true))
		not Fact(name("objazd"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("zakopane");
end

rule "Offer Bieszczady"
	salience 10000
	when
		Fact(name("mountains"), value(true))
		not Fact(name("exotic"), value(true))
		not Fact(name("objazd"), value(true))
	then
		Communication.askQuestion("bieszczady");
end

rule "Offer Slowacja"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("active"), value(false))
		Fact(name("mountains"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("slowacja");
end

rule "Offer Chile-Argentyna"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		not Fact(name("south_america"), value(false))
		Fact(name("exotic"), value(true))
		(or
			(and
				Fact(name("jungle"), value(true))
				Fact(name("south_america"), value(true))
			)
			(and
				Fact(name("mountains"), value(true))
				Fact(name("seaside"), value(true))
			)
		)
		not Fact(name("fear_earthquakes"), value(true))
	then
		Communication.askQuestion("chile_argentyna");
end

rule "Offer narciarstwo i plaza w Chile"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("exotic"), value(true))
		not Fact(name("south_america"), value(false))
		Fact(name("active"), value(true))
		Fact(name("mountains"), value(true))
		Fact(name("seaside"), value(true))
		not Fact(name("fear_earthquakes"), value(true))
	then
		Communication.askQuestion("narciarstwo_plaza_andy");
end

rule "Offer Majowie"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("south_america"), value(true))
		(or
			(and
				Fact(name("exotic"), value(true))
				Fact(name("jungle"), value(true))
			)
	    Fact(name("sightseeing"), value(true))
		)
		not Fact(name("mountains"), value(false))
		not Fact(name("fear_earthquakes"), value(true))
	then
		Communication.askQuestion("majowie");
end

rule "Offer wspinaczka w Himalajach"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("climbing"), value(true))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("himalaje");
end

rule "Offer Alpy"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("skiing"), value(true))
		Fact(name("mountains"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("alpy");
end

rule "Offer poszukiwacze"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("exotic"), value(true))
		not Fact(name("fear_earthquakes"), value(true))
		Fact(name("objazd"), value(true))
    Fact(name("sightseeing"), value(true))
	then
		Communication.askQuestion("majowie");
end

rule "Offer Baleal"
	salience 10000
	when
		Fact(name("max_price"), intValueGreaterThan(1500))
		not Fact(name("poland"), value(true))
		Fact(name("surfing"), value(true))
		Fact(name("long_flight"), value(false))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("baleal");
end

rule "Offer Taghazout"
	salience 10000
	when
		Fact(name("max_price"), intValueGreaterThan(1500))
		not Fact(name("poland"), value(true))
		Fact(name("surfing"), value(true))
		Fact(name("long_flight"), value(false))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("taghazout");
end

rule "Offer weekend w Poznaniu"
	when
		Fact(name("max_price"), intValueGreaterThan(200))
		Fact(name("max_price"), intValueLessThan(1000))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("poznan");
end

rule "Offer Chiny"
	salience 10000
	when
		Fact(name("objazd"), value(true))
		Fact(name("orient"), value(true))
		Fact(name("long_flight"), value(true))
  	Fact(name("sightseeing"), value(true))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("chiny");
end

rule "Offer Nippon"
	salience 10000
	when
		Fact(name("orient"), value(true))
		Fact(name("long_flight"), value(true))
  	Fact(name("sightseeing"), value(true))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("nippon");
end

rule "Offer Egipt"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(1200))
  	Fact(name("active"), value(false))
  	Fact(name("seaside"), value(true))
  	Fact(name("sightseeing"), value(true))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("egipt");
end

rule "Offer Madryt"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(1200))
		Fact(name("sightseeing"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("madryt");
end

rule "Offer Marbella"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(2000))
		Fact(name("water_skiing"), value(true))
		not Fact(name("jungle"), value(true))
	then
		Communication.askQuestion("marbella");
end

rule "Offer Szczecin"
	salience 10000
	when
		not Fact(name("sightseeing"), value(true))
		not Fact(name("objazd"), value(true))
		Fact(name("water_skiing"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("szczecin");
end

rule "Offer splyw_dunajcem"
	salience 10000
	when
		Fact(name("max_price"), intValueGreaterThan(500))
		Fact(name("canoeing"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("splyw_dunajcem");
end

rule "Offer Slowenia"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(1000))
		Fact(name("canoeing"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("slowenia");
end

rule "Offer Wieden-Bratyslawa"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(800))
		Fact(name("sightseeing"), value(true))
		not Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("wieden_bratyslawa");
end

rule "Offer Broadway"
	salience 10000
	when
		not Fact(name("poland"), value(true))
		Fact(name("max_price"), intValueGreaterThan(6000))
		Fact(name("sightseeing"), value(true))
		not Fact(name("exotic"), value(true))
		Fact(name("long_flight"), value(true))
	then
		Communication.askQuestion("broadway");
end
