package rules

import com.agency.*;

rule "Offer Greece"
    when
    	Fact(name("seaside"), value(true));
    then
    	Communication.askQuestion("greece");
end

rule "Offer Turkey"
    when
    	Fact(name("seaside"), value(true));
    then
    	Communication.askQuestion("turkey");
end

rule "Offer Kolobrzeg"
	when
		Fact(name("seaside"), value(true));
	then
		Communication.askQuestion("kolobrzeg");
end

rule "Offer Zakopane"
	when
		Fact(name("seaside"), value(false));
	then
		Communication.askQuestion("zakopane");
end