package rules
 
import com.sample.DroolsTest.*;
import com.agency.*;

rule "Initialize Thinking"
	when
	then
		Communication.askQuestion("seaside");
		//Communication.askQuestion("cost");
		//Communication.askQuestion("boarding");
end

rule "Place Chosen"
	when
		Fact(name("chosen"), value(true));
	then
		Communication.showMessage("chosen");
		drools.halt();
end

rule "No place Chosen"
	salience -1
	when
	then
		Communication.showMessage("not_chosen");
		drools.halt();
end		