package rules

import com.sample.DroolsTest.*;
import com.agency.*;



rule "Place Chosen"
	salience 20000
	when
		Fact(name("chosen"), value(true))
	then
		Communication.showMessage("chosen");
		drools.halt();
end

rule "No place Chosen"
	salience -1
	when
	then
		Communication.showMessage("not_chosen");
		drools.halt();
end



rule "Ask seaside"
	when
		not
		(and
			Fact(name("mountains"), value(true))
			Fact(name("poland"), value(true))
		)
	then
		Communication.askQuestion("seaside");
end

rule "Ask mountains"
	when
		not
		(and
			Fact(name("seaside"), value(true))
			Fact(name("poland"), value(true))
		)
	then
		Communication.askQuestion("mountains");
end

rule "Ask active"
	when
	then
		Communication.askQuestion("active");
end

rule "Ask objazd"
	when
		Fact(name("active"), value(true))
	then
		Communication.askQuestion("objazd");
end

rule "Ask sightseeing"
	when
		(or
			Fact(name("objazd"), value(true))
			Fact(name("active"), value(false))
		)
	then
		Communication.askQuestion("sightseeing");
end

rule "Ask exotic"
	when
		Fact(name("max_price"), intValueGreaterThan(5000))
	then
		Communication.askQuestion("exotic");
end

rule "Ask fear_earthquakes"
	when
		Fact(name("exotic"), value(true))
	then
		Communication.askQuestion("fear_earthquakes");
end

rule "Ask orient"
	when
		not Fact(name("poland"), value(true))
		not Fact(name("south_america"), value(true))
		not Fact(name("africa"), value(true))
		Fact(name("exotic"), value(true))
		Fact(name("fear_earthquakes"), value(false))
	then
		Communication.askQuestion("orient");
end

rule "Ask max price"
	when
	then
		Communication.askQuestion("max_price");
end

rule "Ask jungle"
	when
		Fact(name("active"), value(true))
		Fact(name("exotic"), value(true))
		not Fact(name("poland"), value(true))
	then
		Communication.askQuestion("jungle");
end

rule "Ask South America"
	when
		Fact(name("jungle"), value(true))
		not Fact(name("africa"), value(true))
		not Fact(name("poland"), value(true))
	then
		Communication.askQuestion("south_america");
end

rule "Ask Africa"
	when
		Fact(name("jungle"), value(true))
		not Fact(name("south_america"), value(true))
		not Fact(name("poland"), value(true))
	then
		Communication.askQuestion("africa");
end

rule "Ask poland"
	when
		Fact(name("exotic"), value(false))
	then
		Communication.askQuestion("poland");
end

rule "Ask surfing"
	salience 1
	when
		Fact(name("active"), value(true))
		Fact(name("seaside"), value(true))
	then
		Communication.askQuestion("surfing");
end


rule "Ask climbing"
	salience 1
	when
		Fact(name("active"), value(true))
		Fact(name("mountains"), value(true))
	then
		Communication.askQuestion("climbing");
end

rule "Ask skiing"
	salience 1
	when
		Fact(name("active"), value(true))
		Fact(name("mountains"), value(true))
	then
		Communication.askQuestion("skiing");
end

rule "Ask long_flight"
	when
		not Fact(name("poland"), value(true))
	then
		Communication.askQuestion("long_flight");
end



